version: 2
jobs:
  build:
    docker:
      # Test and code run in _other_ docker containers, so mostly doesn't matter
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            touch .env
            docker-compose build data-workspace
            docker-compose -f docker-compose-test.yml build
            docker-compose -f docker-compose-test.yml run data-workspace-test python3 -m unittest test.test
            docker-compose -f docker-compose-test.yml run data-workspace-test django-admin test /dataworkspace/dataworkspace
