version: 2

jobs:
  docker-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run test
          command: |
            touch .envs/dev.env
            make docker-test
  check-linting:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run static checks
          command: |
            touch .envs/dev.env
            make docker-lint

workflows:
  version: 2
  build:
    jobs:
      - docker-test
      - check-linting
